In [1]:
import requests
import pandas as pd
from tqdm import tqdm
from bs4 import BeautifulSoup
link="https://books.toscrape.com/catalogue/page-1.html"

In [2]:
data=[]
for i in tqdm(range(1,51)):

    #creating link for every page 
    link="https://books.toscrape.com/catalogue/page-"+str(i)+".html"

    #sending request for the pages
    res=requests.get(link)

    # creating soup for the page
    soup=BeautifulSoup(res.text,"html.parser")
    for sp in soup.find_all("li",class_="col-xs-6 col-sm-4 col-md-3 col-lg-3"):
        img_link  ="https://books.toscrape.com/"+sp.find("img").get("src")
        book_link ="https://books.toscrape.com/catalogue/"+sp.find_all("a")[-1].get("href")
        title     = sp.find_all("a")[-1].get("title")
        rating    = sp.find("p").get("class")[-1]
        price   = sp.find("p",class_="price_color").text[1:]
        stock=sp.find("p",class_="instock availability").text.strip()

    #saving the crspe data in the list
        data.append([title,rating,stock,img_link,book_link,price])

100%|██████████| 50/50 [01:12<00:00,  1.45s/it]

In [3]:
len(data)

1000

In [4]:
df=pd.DataFrame(data,columns=["title","rating","stock","img_link","book_link","price"])
# df.to_csv("book_scrapping.csv",index=False)
df

,title,rating,stock,img_link,book_link,price
0,A Light in the Attic,Three,In stock,https://books.toscrape.com/../media/cache/2c/d...,https://books.toscrape.com/catalogue/a-light-i...,£51.77
1,Tipping the Velvet,One,In stock,https://books.toscrape.com/../media/cache/26/0...,https://books.toscrape.com/catalogue/tipping-t...,£53.74
2,Soumission,One,In stock,https://books.toscrape.com/../media/cache/3e/e...,https://books.toscrape.com/catalogue/soumissio...,£50.10
3,Sharp Objects,Four,In stock,https://books.toscrape.com/../media/cache/32/5...,https://books.toscrape.com/catalogue/sharp-obj...,£47.82
4,Sapiens: A Brief History of Humankind,Five,In stock,https://books.toscrape.com/../media/cache/be/a...,https://books.toscrape.com/catalogue/sapiens-a...,£54.23
...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,One,In stock,https://books.toscrape.com/../media/cache/96/e...,https://books.toscrape.com/catalogue/alice-in-...,£55.53
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Four,In stock,https://books.toscrape.com/../media/cache/09/7...,https://books.toscrape.com/catalogue/ajin-demi...,£57.06
997,A Spy's Devotion (The Regency Spies of London #1),Five,In stock,https://books.toscrape.com/../media/cache/1b/5...,https://books.toscrape.com/catalogue/a-spys-de...,£16.97
998,1st to Die (Women's Murder Club #1),One,In stock,https://books.toscrape.com/../media/cache/2b/4...,https://books.toscrape.com/catalogue/1st-to-di...,£53.98
999,"1,000 Places to See Before You Die",Five,In stock,https://books.toscrape.com/../media/cache/d7/0...,https://books.toscrape.com/catalogue/1000-plac...,£26.08

In [92]:
data=[]
for sp in soup.find_all("li",class_="col-xs-6 col-sm-4 col-md-3 col-lg-3"):
    # print(sp)
    # print("------")
    img_link  =sp.find("img").get("src")
    book_link = sp.find_all("a")[-1].get("href")
    title     = sp.find_all("a")[-1].get("title")
    rating    = sp.find("p").get("class")[-1]
    price   = sp.find("p",class_="price_color").text[1:]
    stock=sp.find("p",class_="instock availability").text.strip()
    
    data.append([title,rating,stock,img_link,book_link,price])
    # print(rating ,"|",title,"|",book_link,"|",img_link,"|",price,"|",available)

In [77]:
df=pd.DataFrame(data,columns=["title","rating","stock","img_link","book_link","price"])
df

,title,rating,stock,img_link,book_link,price
0,A Light in the Attic,Three,In stock,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,a-light-in-the-attic_1000/index.html,£51.77
1,Tipping the Velvet,One,In stock,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,tipping-the-velvet_999/index.html,£53.74
2,Soumission,One,In stock,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,soumission_998/index.html,£50.10
3,Sharp Objects,Four,In stock,../media/cache/32/51/3251cf3a3412f53f339e42cac...,sharp-objects_997/index.html,£47.82
4,Sapiens: A Brief History of Humankind,Five,In stock,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,sapiens-a-brief-history-of-humankind_996/index...,£54.23
...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,One,In stock,../media/cache/96/ee/96ee77d71a31b7694dac6855f...,alice-in-wonderland-alices-adventures-in-wonde...,£55.53
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Four,In stock,../media/cache/09/7c/097cb5ecc6fb3fbe1690cf0cb...,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...,£57.06
997,A Spy's Devotion (The Regency Spies of London #1),Five,In stock,../media/cache/1b/5f/1b5ff86f3c75e51e24c573d3f...,a-spys-devotion-the-regency-spies-of-london-1_...,£16.97
998,1st to Die (Women's Murder Club #1),One,In stock,../media/cache/2b/41/2b4161c5b72a4ae386b644682...,1st-to-die-womens-murder-club-1_2/index.html,£53.98
999,"1,000 Places to See Before You Die",Five,In stock,../media/cache/d7/0f/d70f7edd92705c45a82118c3f...,1000-places-to-see-before-you-die_1/index.html,£26.08