<a href="https://colab.research.google.com/github/mc4830913-max/python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
first=[1,2,3,4,5]
pd.Series(first)

#through numpy
arr=np.array(["3","5","9","5"])
pd.Series(arr)
pd.Series(data=[1,2,3,4,5],index=["apple","banana","litchi","govava","orange"])

apple     1
banana    2
litchi    3
govava    4
orange    5
dtype: int64

In [ ]:
dictoinary={1:"Monika",2:"radha",3:"muskan",4:"Nidhi" }
pd.Series(dictoinary)

1    Monika
2     radha
3    muskan
4     Nidhi
dtype: object

In [ ]:
pd.Series("mona").repeat(5)

0    mona
0    mona
0    mona
0    mona
0    mona
dtype: object

In [ ]:
pd.Series(["mona","vanni"]).repeat([4,3]).reset_index(drop=True)

0     mona
1     mona
2     mona
3     mona
4    vanni
5    vanni
6    vanni
dtype: object

In [ ]:
n=pd.Series(["mona","vanni"]).repeat([4,3]).reset_index(drop=True)
n[4]
n[1:7]
#By last n numbers (start - end-1)
n[1:-2]

1     mona
2     mona
3     mona
4    vanni
dtype: object

In [ ]:
#b) Aggregate function on pandas Series
sr=pd.Series([45,67,83,69,45,78,99])
sr.aggregate("sum")
sr.aggregate("min")
sr.aggregate("max")
sr.aggregate("mean")
sr.aggregate("median")
sr.aggregate("std")
sr.aggregate("var")
sr.aggregate("count")
sr.aggregate("size")
sr.aggregate("mode")
sr.aggregate("nunique")
sr.aggregate([min,max,sum])

/tmp/ipython-input-1684/2756032019.py:14: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  sr.aggregate([min,max,sum])
/tmp/ipython-input-1684/2756032019.py:14: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  sr.aggregate([min,max,sum])
/tmp/ipython-input-1684/2756032019.py:14: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sr.aggregate([min,max,sum])

min     45
max     99
sum    486
dtype: int64

In [ ]:
#c) Series absolute function
sr=pd.Series([45,-67,83,-69,45.76,78,99])
sr.abs()
#f) Between Function
print(sr.between(10,90))

0     True
1    False
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [ ]:
#d) Appending Series
sr1=[1,3,4,5]
sr2=[6,7,8,9]
# sr3=append([sr2,sr1])
# pd.Series(sr3)
#this is not working

In [ ]:
#e) Astype function
pd.Series(sr2).astype("float")
# type(sr1[0])

0    6.0
1    7.0
2    8.0
3    9.0
dtype: float64

In [ ]:
#f) Between Function
sr=pd.Series([45,-67,83,-69,45.76])
sr.between(-70,1)

0    False
1     True
2    False
3     True
4    False
dtype: bool

 Upper and Lower Function

 Len function

 Strip Function

 Split Function

 Contains Function

 Replace Function

 Count Function

 Startswith and Endswith Function

 Find Finction

In [ ]:
#g) All strings functions can be used to extract or modify texts in a series
ser=pd.Series(["red colour","blue","orange","engineering","    graduate","geeks for geeks"])
print(ser.str.upper())
print("_"*20)
print(ser.str.lower())
print("_"*20)
for i in ser:
  print(i,len(i))
print("_"*20)
ser = ser.str.strip()
for i in ser:
    print(i , len(i))
print("_"*20)
print(ser.astype("str"))
print("_"*20)
print(ser.str.split())
print(ser.str.split()[5])

0         RED COLOUR
1               BLUE
2             ORANGE
3        ENGINEERING
4           GRADUATE
5    GEEKS FOR GEEKS
dtype: object
____________________
0         red colour
1               blue
2             orange
3        engineering
4           graduate
5    geeks for geeks
dtype: object
____________________
red colour 10
blue 4
orange 6
engineering 11
    graduate 12
geeks for geeks 15
____________________
red colour 10
blue 4
orange 6
engineering 11
graduate 8
geeks for geeks 15
____________________
0         red colour
1               blue
2             orange
3        engineering
4           graduate
5    geeks for geeks
dtype: object
____________________
0          [red, colour]
1                 [blue]
2               [orange]
3          [engineering]
4             [graduate]
5    [geeks, for, geeks]
dtype: object
['geeks', 'for', 'geeks']

In [ ]:
ser = pd.Series(["Eshant Das","Data@Science","Geeks for Geeks",'Hello@World','Machine Learning'])
# for i in ser:
print(pd.Series(ser))
print("_"*20)
print(ser.str.replace('@','   '))
print("_"*20)
print(ser.str.count('e'))
print("_"*20)
print(ser.str.startswith('G'))
print("_"*20)
print(ser.str.endswith('s'))
print("_"*20)
print(ser.str.find("Hello@World"))

0          Eshant Das
1        Data@Science
2     Geeks for Geeks
3         Hello@World
4    Machine Learning
dtype: object
____________________
0          Eshant Das
1      Data   Science
2     Geeks for Geeks
3       Hello   World
4    Machine Learning
dtype: object
____________________
0    0
1    2
2    4
3    1
4    2
dtype: int64
____________________
0    False
1    False
2     True
3    False
4    False
dtype: bool
____________________
0     True
1    False
2     True
3    False
4    False
dtype: bool
____________________
0   -1
1   -1
2   -1
3    0
4   -1
dtype: int64

In [ ]:
#h) Converting a Series to List
ser.to_list()
#Creating Data Frames
s1=pd.Series(["lcet",'is','college',"of",'engineering','at','chandigarh','road'])
s1.str.upper()
pd.DataFrame(s1)

s2=[['lcet','ludhiana'],['cu',"chandigarh"],['lpu','amritsar']]
pd.DataFrame(s2)


data = {'name':['Tom', 'nick', 'krish', 'jack'], 'age':[20, 21, 19, 18]}
pd.DataFrame(data)

data = { 'Name'         :pd.Series(['Jai', 'Princi', 'Gaurav', 'Anuj']),
         'Age'          :[27, 24, 22, 32],
         'Address'      :['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
         'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df=pd.DataFrame(data)
df[['Age','Address']]

#slicing in data frame using loc in iloc
data = {'one'   : pd.Series([1, 2, 3, 4]),
        'two'   : pd.Series([10, 20, 30, 40]),
        'three' : pd.Series([100, 200, 300, 400]),
        'four'  : pd.Series([1000, 2000,3000, 4000])}
df=pd.DataFrame(data)
df.loc[0:1,'three':'four']
df.iloc[0:-1,0:-1]
df.iloc[1:,1:]
df.iloc[[2,3],[1,3]]

#c) Slicing Using Conditions
df.loc[df['one']>1,['four','three','one']]

#c) Column Addition in DataFrame
l=[45,65,75,55]
df["five"]=l
df

sr=pd.Series([23,43,53,73])
df["six"]=sr
df
df["seven"]=df["two"]+12
df

del df["five"]
df

df.pop('one')
df

   two  three  four  six  seven
0   10    100  1000   23     22
1   20    200  2000   43     32
2   30    300  3000   53     42
3   40    400  4000   73     52

In [6]:
#addtition of rows
df1=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[4,8],[9,6]],columns=['a','b'])
df3=pd.concat([df1,df2]).reset_index(drop=True)
df3
data1 = {'one'   : pd.Series([1, 2, 3, 4]),
        'two'   : pd.Series([10, 30, 30, 40]),
        'three' : pd.Series([100, 200, 300, 400]),
        'four'  : pd.Series([1000, 2000,3000, 4000])}
df4=pd.DataFrame(data1)
df4

# df4.drop([0,1],axis=0,inplace=True)
# df4
# df4.drop(['one','three'],axis=1,inplace=True)
# df4

# Transposing a DataFrame
print(df4.T)
df4.axes
df4.ndim #number of dimension
df4.dtypes
df4.shape
df4.sum()
df4.mean()
df4.median()
df4.var()
df4.min()
df4.max()
df4.std()
print('two',data1['two'].mode())
df4.describe()

def add_(i,j):
  return i+j
df4.pipe(add_,(10))


def mean_(col):
  return col.mean()
def square(i):
  return i**2
df4.pipe(mean_).pipe(square)


df4.apply(np.mean)
df4.apply(lambda x:x.max())
df4.apply(lambda x:x.min())
df4.apply(lambda x:x.max()-x.min())
df4.apply(lambda x:x*2.5)

          0     1     2     3
one       1     2     3     4
two      10    30    30    40
three   100   200   300   400
four   1000  2000  3000  4000
two 0    30
dtype: int64

    one    two   three     four
0   2.5   25.0   250.0   2500.0
1   5.0   75.0   500.0   5000.0
2   7.5   75.0   750.0   7500.0
3  10.0  100.0  1000.0  10000.0

In [ ]:
d = { 'Name'  :pd.Series(['Tom','Jerry','Spike','Popeye','Olive','Bluto','Mickey']),
      'Age'   :pd.Series([10,12,14,30,28,33,15]),
      'Height':pd.Series([3.25,1.11,4.12,5.47,6.15,6.67,2.61])}
df=pd.DataFrame(d)
df.head(3)
df.tail(3)
df.empty

False

In [22]:
de=pd.DataFrame({'A':[1.2,4.6,5.6],
                 'B':[6.7,3.5,9.3]})
df=de.applymap(np.int64)
print(df)
df = pd.DataFrame({ 'A': [1.2, 3.4, 5.6],
                    'B': [7.8, 9.1, 2.3]})

# df_1 = df.applymap(np.int64)
# print(df_1)
print("*"*30)
df1=de.apply(lambda row:row.mean(),axis=0)
print(df1)

print(df4.reindex([1,0,3,2]))
print(df4.reindex(columns=['four','one','three','two']))
print("*"*40)

data1 = {'one'   : pd.Series([1, 2, 0, 4]),
        'two'   : pd.Series([10, 30, 30, 40]),
        'three' : pd.Series([180, 60, 120, 400]),
        'four'  : pd.Series([1000, 2000,3000, 4000])}
dff=pd.DataFrame(data1)
dff.rename(columns={'one':'first','two':'Second','three':'third','four':'forth'}
          ,inplace=True,index={0:'1',1:'2',2:'3',3:'4'})
dff

dff.sort_values(by='third',ascending=True)
dff.sort_values(by=['first','third'])
dff.sort_values(by=['first'],kind='heapsort')

   A  B
0  1  6
1  4  3
2  5  9
******************************
A    3.8
B    6.5
dtype: float64
   one  two  three  four
1    2   30    200  2000
0    1   10    100  1000
3    4   40    400  4000
2    3   30    300  3000
   four  one  three  two
0  1000    1    100   10
1  2000    2    200   30
2  3000    3    300   30
3  4000    4    400   40
****************************************

/tmp/ipykernel_306/3020737557.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df=de.applymap(np.int64)

   first  Second  third  forth
3      0      30    120   3000
1      1      10    180   1000
2      2      30     60   2000
4      4      40    400   4000

In [53]:
cricket = {'Team'   : ['India', 'India', 'Australia', 'Australia', 'SA', 'SA', 'SA', 'SA', 'NZ', 'NZ', 'NZ', 'India'],
           'Rank'   : [2, 3, 1,2, 3,4 ,1 ,1,2 , 4,1,2],
           'Year'   : [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
           'Points' : [876,801,891,815,776,784,834,824,758,691,883,782]}
df=pd.DataFrame(cricket)
df

df.groupby('Year').groups
df.groupby(['Team','Year']).get_group(('India',2017))
df.groupby('Team').sum()['Points']
# df.groupby('Team').max()['Points']
# df.groupby('Team').min()['Points']
df.groupby('Team').sum()['Points'].sort_values(ascending=True)
groups=df.groupby('Team')
groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
df.groupby('Team').filter(lambda x:len(x)==3)  #disply number of item appear in list
df.groupby('Rank').filter(lambda x:len(x)==4)

/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function mean at 0x790cc0bd5a80> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function median at 0x790cbd921b20> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function std at 0x790cc0bd5bc0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function var at 0x790cc0bd5d00> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function max at 0x790cc0bd5080> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])
/tmp/ipykernel_306/508452440.py:15: FutureWarning: The provided callable <function min at 0x790cc0bd51c0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  groups['Points'].agg([np.mean,np.median,np.std,np.var,np.max,np.min])

         Team  Rank  Year  Points
0       India     2  2014     876
2   Australia     1  2014     891
3   Australia     2  2015     815
6          SA     1  2016     834
7          SA     1  2017     824
8          NZ     2  2016     758
10         NZ     1  2015     883
11      India     2  2017     782